name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t bg-mule-se:4.4.0 .

      - name: Run Docker container
        run: docker run -d --name bg-mule-se-440 -p "8081:8081" bg-mule-se:4.4.0

      - name: Copy Mule application JAR to Docker container
        run: docker cp target/crud_demo-1.0.0-SNAPSHOT-mule-application.jar bg-mule-se-440:/opt/mule/apps
