name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Maven dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn test

    - name: Package application
      run: mvn package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: prashanthbasavaraju1411/Mulesoft:latest

    # - name: Deploy to MuleSoft CloudHub
    #   env:
    #     MULESOFT_USERNAME: ${{ secrets.MULESOFT_USERNAME }}
    #     MULESOFT_PASSWORD: ${{ secrets.MULESOFT_PASSWORD }}
    #   run: |
    #     # Replace with your deployment command for MuleSoft
    #     echo "Deploying to MuleSoft CloudHub..."
